### ISSUE TITLE
Any build after November 2017 does not boot on Y635-L01

### ISSUE THREAD

**Issue by julianxhokaxhiu** [HUAWEI-MSM8916/android_kernel_huawei_hwY635#1]
Hi,

probably you have noticed it as well, but since November 2017, any build is coming out with a 50% lighter Kernel in size. I'm not sure if this means something good or bad, but the result is that the Kernel does not work on top of Y635-L01.

As a workaround at the current status I am always flashing a new build out of my own CICD, and an old Kernel from one of your [last October builds](https://androidfilehost.com/?fid=745849072291678029) where the kernel is around 15MB in size. By flashing that `boot.img` manually through TWRP, the ROM starts successfully ( even on last December builds ).

Any idea why is this happening?

**Comment by AndroidC-512L** [comment]
carlos has dropped the support but i am trying to resume it from where it left

**Comment by AndroidC-512L** [comment]
and i will fix that issue. check my profile to follow progress

**Comment by julianxhokaxhiu** [comment]
Thank you!

**Comment by julianxhokaxhiu** [comment]
@AndroidC-512L I am following the progress on your repo, but I never saw a commit related to this issue. Have you managed to fix it or at least, find out the reason why it is happening?

**Comment by AndroidC-512L** [comment]
its because someone who i met in telegram found how to fix the kernel problem. additionaly i found the cause of the battery drain and he fixed it too. the repos in my account has everything working but the roms that have this were only shared in our telegram group but i will share a google drive link with that new roms as soon as i can

**Comment by julianxhokaxhiu** [comment]
Would be nice to know if you can merge those patches actually :) I'm building it on my own server at the moment. Thank you in advance!

**Comment by julianxhokaxhiu** [comment]
This phone is no more used at least by me, so I don't have this issue anymore. Although it still persists. Good luck for the future.
